<?
   require_once("public/components/head.php");
   require_once("public/components/main.php");
   require_once("public/components/aboutUs.php");
   require_once("public/components/news.php");
   require_once("public/components/gallery.php");
   require_once("public/components/diary.php");
   require_once("public/components/error.php");
   require_once("public/authentication/users.php");
   require_once("public/authentication/classes.php");
   require_once("public/authentication/journal.php");
?>